//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thue_san_the_thao.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Bookings = new HashSet<Booking>();
            this.Prices = new HashSet<Price>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int FieldID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public string FieldName { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> FieldDate { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
