//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thue_san_the_thao.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public Nullable<int> FieldID { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public Nullable<decimal> Price1 { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
